-- PSICOSENATICO V4 inventory data renderer
local P=_G.PSICO_INVENTORY_PANEL_V4;if not(P and P.List and P.Status)then error('V4 UI missing')end
local RS=game:GetService('ReplicatedStorage')
local function path(s)local x=RS;for p in s:gmatch('[^%.]+')do x=x and x:FindFirstChild(p)end;return x end
local function req(s)local m=path(s);if not(m and m:IsA('ModuleScript'))then return nil end;local ok,v=pcall(require,m);return ok and v or nil end
local Save=req('Shared.Save')or req('Data.Save');local Eggs=req('Shared.Util.EggRecords');local Assets=req('Data.Assets')
local function call(t,n,...)if type(t)~='table'or type(t[n])~='function'then return nil end;local ok,v=pcall(t[n],...);if ok then return v end;ok,v=pcall(t[n],t,...);return ok and v or nil end
local function norm(v)return tostring(v or''):lower():gsub('[%s_%-%.:/%[%]%(%)\'•]','')end
local function compact(n)n=tonumber(n);if not n then return'?'end;local a=math.abs(n);if a>=1e12 then return('%.2fT'):format(n/1e12)elseif a>=1e9 then return('%.2fB'):format(n/1e9)elseif a>=1e6 then return('%.2fM'):format(n/1e6)elseif a>=1e3 then return('%.1fK'):format(n/1e3)end;return tostring(math.floor(n+.5))end
local function recval(r,k)if type(r)~='table'then return nil end;if r[k]~=nil then return r[k]end;local i=type(r.ItemData)=='table'and r.ItemData;if i then return i[k]end end
local function rarity(cat)local target=norm(cat);local function scan(tbl)for k,c in pairs(tbl or{})do if type(c)=='table'and type(c.Rarity)=='table'and(norm(k)==target or norm(c.DisplayName)==target)then return c.Rarity.DisplayName or c.Rarity._id,c end end end;if type(Assets)=='table'and type(Assets.ByRarity)=='table'then for _,g in pairs(Assets.ByRarity)do local r,c=scan(g);if r then return r,c end end end;return nil,nil end
local colors={Eternal=Color3.fromRGB(245,71,255),Divine=Color3.fromRGB(52,255,238),Secret=Color3.fromRGB(245,245,245),Cosmic=Color3.fromRGB(150,67,255),Mythic=Color3.fromRGB(255,71,121),Legendary=Color3.fromRGB(255,174,58)}
local cards={};local function clear()for _,c in ipairs(cards)do pcall(function()c:Destroy()end)end;cards={}end
local function label(p,t,pos,size,sz)local x=Instance.new('TextLabel');x.BackgroundTransparency=1;x.Position=pos;x.Size=size;x.Font=Enum.Font.Gotham;x.Text=t;x.TextSize=sz;x.TextColor3=Color3.fromRGB(225,232,245);x.TextXAlignment=Enum.TextXAlignment.Left;x.Parent=p;return x end
local function render()clear();local sd=Save and call(Save,'Get');local inv=type(sd)=='table'and sd.EggInventory;if type(inv)~='table'then P.Status.Text='EggInventory indisponível';return end;local rows={};for key,r in pairs(inv)do if type(r)=='table'then local cat=tostring(recval(r,'AssetCategory')or recval(r,'Category')or recval(r,'Name')or'?');local rar,cfg=rarity(cat);rows[#rows+1]={key=key,r=r,cat=cat,rar=rar or tostring(r.Rarity or'?'),cfg=cfg,w=tonumber(call(Eggs,'WeightKg',r)),wl=call(Eggs,'WeightLabel',r),sell=tonumber(call(Eggs,'SellPrice',r))}end end;table.sort(rows,function(a,b)return(a.w or 0)>(b.w or 0)end);P.Status.Text=('Ovos:%d • lista independente'):format(#rows);for i,e in ipairs(rows)do local c=Instance.new('Frame');c.BackgroundColor3=Color3.fromRGB(25,34,50);c.BorderSizePixel=0;c.Size=UDim2.new(1,-6,0,82);c.LayoutOrder=i;c.Parent=P.List;cards[#cards+1]=c;local cr=Instance.new('UICorner');cr.CornerRadius=UDim.new(0,10);cr.Parent=c;local st=Instance.new('UIStroke');st.Thickness=2;st.Color=colors[e.rar]or Color3.fromRGB(74,112,190);st.Parent=c;local title='Ovo'..(e.wl and(' '..tostring(e.wl))or(e.w and(' ('..compact(e.w)..'Kg)')or''));local a=label(c,title,UDim2.new(0,14,0,9),UDim2.new(1,-28,0,24),12);a.Font=Enum.Font.GothamBold;a.TextColor3=colors[e.rar]or Color3.fromRGB(235,240,250);label(c,(e.rar or'?')..' • Conteúdo: '..e.cat,UDim2.new(0,14,0,34),UDim2.new(1,-28,0,20),9);local m={};if e.cfg and tonumber(e.cfg.EarningRate)then m[#m+1]='$'..compact(e.cfg.EarningRate)..'/s'end;if e.sell then m[#m+1]='Valor $'..compact(e.sell)end;label(c,table.concat(m,' • '),UDim2.new(0,14,0,57),UDim2.new(1,-28,0,18),8)end end
P.Refresh.Activated:Connect(render);render()
